### PR TITLE
[11.0][UPT]Add tags to sales analysis

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Add tags to Sales Analysis

### CODE REVIEW

**Review by HviorForgeFlow — APPROVED** [review]
LGTM :+1: Maybe change INNER JOIN by LEFT JOIN to ensure you don't have duplicates, but I don't think this will affect to correct performing.

**Comment by AaronHForgeFlow** [comment]
Did you detect duplicates? Perhaps we can use `DISTINCT ON (so.id, tag_id)` clause but I am not sure if this is possible.

**Comment by HviorForgeFlow** [comment]
@jbeficent @lreficent @mreficent @aheficent

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM :+1:

**Pull request merged**
