### PR TITLE
[12.0][MIG] mrp_bom_standard_cost

### PR DESCRIPTION
**Pull request by HviorForgeFlow**

### CODE REVIEW

**Review by AdriaGForgeFlow — CHANGES_REQUESTED** [review]
Odoo v12 does not support .less styling files anymore, they should be translated to .scss

**Comment by AdriaGForgeFlow** [comment]
You need to add also a security rule in the csv to be able to edit the labour and overhead costs table in the BoM. Something like this:
access_mrp_bom_cost_manager,access_mrp_bom_cost_manager,model_mrp_bom_cost,mrp.group_mrp_manager,1,1,1,1

**Comment by HviorForgeFlow** [comment]
@ageficent I had an issue with scss, I can't figure out how to translate las fixup commit.

**Comment by AdriaGForgeFlow** [comment]
> @ageficent I had an issue with scss, I can't figure out how to translate las fixup commit.

I think you should use:
`justify-content: flex-end;`

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review and functional test :+1:

**Pull request merged**
