### PR TITLE
[11.0][ADD]product_bom_standard_cost_align

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Uses the same wizard that updates the standard cost to another value. The only difference is it proposes the bom_standard_cost as new price.

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
The problem with this is that it only works for one product at a time. This can be very time consuming. Perhaps we can make another wizard that allows to do it on a mass basis, by calling each time to this wizard you just extended? So as a user you can select a list of products from the tree view and then go to "Actions > Align to BOM standard cost".

**Comment by JordiBForgeFlow** [comment]
The only parameter that the user should enter is what contra-account should be used for the adjustment.

**Comment by JordiBForgeFlow** [comment]
@aheficent I miss to see the cost of the bom in the product tree view.

**Comment by AaronHForgeFlow** [comment]
@jbeficent I'll add that.BTW the filter "Misalignment with BOM cost" is still not working. I will check.

**Comment by AaronHForgeFlow** [comment]
@jbeficent Ready to review now :)

**Review by LoisRForgeFlow — APPROVED** [review]

**Pull request merged**
