### PR TITLE
[11.0][IMP] ao_crm: send contents of message when crm.lead is assigned

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
In lead/opportunities, send contents of message when the record is assigned

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
Can you clarify why migrating https://code.alephobjects.com/source/ao-odoo/browse/9.0/mail_auto_follower_notify/models/mail_thread.py is not an option?

The module you created is specific to leads. But we need that for other models, such as crm.helpdesk. The old module was working for any module.

**Comment by LoisRForgeFlow** [comment]
@jbeficent that module was to force the notification when you where assigned to a lead. In v11, this is standard and works out of the box.

The issue now is that in v9 the notification included the original customer email in the assignment notification mail, in v11 it is just a link to the Odoo lead. This aims to add that original customer mail in the notification to the user assigned to the lead.

**Review by LoisRForgeFlow — APPROVED** [review]
Tested it right now, works perfectly! :clap:

**Comment by LoisRForgeFlow** [comment]
I won't merge right now, waiting their approval and maybe I'll add some test too.

**Pull request merged**
