### PR TITLE
[11.0][MIG] ao_stock_picking_operation_quick_change

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
Can you paste a screenshot of the feature in your testing instance? Thanks!

And try to add the oca dependencies file to see if travis goes green  :green_apple:

**Comment by LoisRForgeFlow** [comment]
Great, now it's green. Let's wait the merge of `stock_picking_operation_quick_change`.

**Comment by LoisRForgeFlow** [comment]
stock_picking_operation_quick_change has been merged, update accordingly.

**Comment by MiquelRForgeFlow** [comment]
done

**Review by LoisRForgeFlow — APPROVED** [review]
Tested locally, works as expected! :+1:

**Pull request merged**
